### ISSUE TITLE
Gifting feature not working on self-hosted instance

### ISSUE THREAD

**Issue by bitcointxoko** [MutinyWallet/mutiny-deploy#5]
### Describe the issue: 

Opening the gift link created in the self-hosted instance brings up an nginx 404 not found error. It is also possible to create gifts with zero wallet balance. 

### Expected behaviour: 

Opening the gift link brings up a (self-hosted) Mutiny Wallet in which the recipient can redeem the gift. Gifts cannot be created with zero wallet balance. 

### Steps to reproduce: 

1. I have followed the deployment instructions found in [docs](https://github.com/MutinyWallet/mutiny-deploy/blob/master/docs/setup-docs.md) to deploy Mutiny to a VPS. There is already an instance of nginx running on the VPS before deploying Mutiny, I'm not sure if it causes conflicts, but other features seem to work fine. 
2. Navigate to https://mutiny.bitcointxoko.com and create a gift. It is possible to create a gift with zero balance, which does not seem right. I have added the default Esplora and RGS back into the Servers settings. 
3. Redeem the gift in a browser and observe the 404 not found error. 

### Other info

The following are working: 

- wallet funding
- channel open from Voltage Flow 2.0 LSP
- channel open to own node
- transacting on LN
- zaps

The following are NOT working: 

- gifting
- nostr contacts (missing Primal API)

- cannot access the self-hosted instance at https://mutiny.bitcointxoko.com in Vanadium on GrapheneOS, but works in other browsers. Trying to do this brings up the browser not supporting WebAssembly message and help hint for running iOS in lockdown mode. Loading the official instance of https://app.mutinywallet.com works fine. Since this problem seems tangential, I can create a separate issue if needed.

**Comment by benthecarman** [comment]
Hey sorry about the late reply 

Our next release will fix gifting and nostr contacts, sorry about that.

For Vanadium checkout our [compatibility guide](https://github.com/MutinyWallet/mutiny-web/wiki/Browser-Compatibility), looks like you need Javascript JIT turned on for your url

**Comment by bitcointxoko** [comment]
No worries, excited for the next release!

Enabled Javascript JIT in Vanadium and it works now, cheers
